---
title: "1214作業_人口組"
date: 2022-12-11
author:
- 109204005 社會三 劉人瑜
- 109204018 社會三 李彩瑄
- 109204025 社會三 劉采葳
- 109204035 社會三 黃楷捷
format: 
  html: 
    toc: true
    toc-title: Contents
    toc-location: body
    page-layout: full
    code-overflow: wrap
editor: visual
---

```{r,echo=FALSE}
options(digits = 3)
```

```{r,message = FALSE}
library(dplyr)
library(haven)
library(data.table)
tscs212 <- read_dta('../../../HW/tscs212.dta') |> setDT()
tscs212 <- as_factor(tscs212, levels = "default")
```

## 年齡

### 全國
#### 社會變遷（樣本）
```{r}
ageSet <- tscs212 [!(a2y %in% c('拒答', '不知道')), ]
ageSet[, a2y := as.numeric(as.character(a2y))][, age := 110 - a2y]
ageSet$age <- 110 - as.numeric(ageSet$a2y)
ageSet <- ageSet[age >= 20, ]
ageSet$ageGroups <- cut(ageSet$age,
                        breaks = c(-Inf, 29, 39, 49, 59, 69, 79, 89, 99, Inf),
                        labels = c('20-29', '30-39', '40-49', '50-59', '60-69',
                                   '70-79', '80-89', '90-99', '100以上'))
prop.table(table(ageSet$ageGroups)) * 100
```
#### 內政部人口統計（母體）
```{r}
popAge <- setDT(readxl::read_excel(path = "../../../HW/age.xlsx"))
AG <- names(popAge)[3:13]
AGR <- stringr::str_remove_all(string = AG, pattern = "歲")
popAge <- popAge[, (AGR) := .SD / 總計 * 100, .SDcols = AG]
N <- c(16:24)
popAge[County == "全國", ][,..N]
```


### 六都
#### 社會變遷（樣本）
```{r}
ageSet <- (ageSet[a4acity %in% c('臺北市', '臺中市', '高雄市'), .(groupsCount = .N), by = .(a4acity, ageGroups)]
                 [, groupsFreq := groupsCount / sum(groupsCount), by = .(a4acity)]
                 [, .(groupsFreq = groupsFreq * 100), keyby = .(a4acity, ageGroups)])
dcast(ageSet, a4acity ~ ageGroups, value.var = 'groupsFreq')
```
#### 內政部人口統計（母體）
```{r}
N <- c(1, 16:24)
popAge[County %in% c("臺北市", "臺中市", "高雄市"), ..N]
```

##  性別
### 全國
#### 社會變遷（樣本）

```{r}
(sum(tscs212$a1 == "男") / sum(tscs212$a1 == "女")) * 100
```
#### 內政部人口統計（母體）
```{r,echo=FALSE}
print(98.2)
```
### 六都
#### 社會變遷（樣本）

```{r}
tscs212[a4acity %in% c("高雄市", "臺北市", "臺中市"),
        .(性比例 = sum(a1 == "男") / sum(a1 == "女") * 100), by = .(a4acity)]
```
#### 內政部人口統計（母體）
```{r,echo=FALSE}
sr <- data.frame(性比例 = c(97.2, 90.9, 96.4))
rownames(sr) <- c("高雄市", "臺北市", "臺中市")
sr
```

## 投票行為

### 全國

#### 社會變遷（樣本）

```{r}
opt <- (table(tscs212$j28) |> data.frame())[, 1]
voteSet <- tscs212 [!(j28 %in% opt[7:10]), ]
voteSet[, .(投票率 = sum(j28 %in% opt[1:5]) * 100 / sum(j28 %in% opt[1:6]),
            宋楚瑜得票率 = sum(j28 %in% opt[1]) * 100 / sum(j28 %in% opt[1:5]),
            韓國瑜得票率 = sum(j28 %in% opt[2]) * 100 / sum(j28 %in% opt[1:5]),
            蔡英文得票率 = sum(j28 %in% opt[3]) * 100 / sum(j28 %in% opt[1:5]))]
```

#### 中選會資料（母體）

```{r,echo=FALSE}
data.frame(投票率 = 74.9,
           宋楚瑜得票率 = 4.26, 
           韓國瑜得票率 = 38.61, 
           蔡英文得票率 = 57.13)
```

### 六都

#### 社會變遷（樣本）

```{r}
(voteSet[a4acity %in% c('臺北市', '臺中市', '高雄市'),
         .(投票率 = sum(j28 %in% opt[1:5]) * 100 / sum(j28 %in% opt[1:6]),
           宋楚瑜得票率 = sum(j28 %in% opt[1]) * 100 / sum(j28 %in% opt[1:5]),
           韓國瑜得票率 = sum(j28 %in% opt[2]) * 100 / sum(j28 %in% opt[1:5]),
           蔡英文得票率 = sum(j28 %in% opt[3]) * 100 / sum(j28 %in% opt[1:5])), by = .(a4acity)])
```

#### 中選會資料（母體）

```{r,echo=FALSE}
data.frame(縣市 = c('臺北市', '臺中市', '高雄市'),
           投票率 = c(76.31, 76.36, 77.44),
           宋楚瑜得票率 = c(4.34, 4.99, 3.14), 
           韓國瑜得票率 = c(42.01, 38.06, 34.63), 
           蔡英文得票率 = c(53.64, 56.95, 62.23))
```
